package de.binary101.core.constants.enums;

public enum ResponseEnum {
	ERR_NOT_IMPLEMENTED("-999"),
	ERR_INVALID_RESPONSE("-998"),
	ERR_TOILET_EMPTY("toilett is not full"), // -310
	ERR_NO_SLOT_FOR_FLUSHING("need free backpack slot"), // -307
	ERR_PORTAL_FOUGHT_ALREADY("already fought"), // -106
	ERR_NOBATTLE("-105"),
	ERR_WITCH_NOT_HIGH_ENOUGH("-104"),
	ERR_TOWER_NO_COPYCATS("-101"),
	ERR_TOWER_ITEMMOVE("-100"),
	ERR_TOWER_CLOSED("-98"),
	ERR_NO_CHAT_OVERFLOW("-97"),
	ERR_NO_CHAT_INFO("-96"),
	ERR_GUILD_RANK_WRONG("-95"),
	ERR_LUXURY_ALREADY("-94"),
	ERR_NO_ALBUM("-93"),
	ERR_INVITE_EMAIL_REJECTED("-92"),
	ERR_INVITE_TOO_MANY("-91"),
	ERR_INVITE_NOT_VALIDATED("-90"),
	ERR_INVENTORY_FULL_ADV("-86"),
	ERR_MSG_NOT_VALIDATED("valid email required"), // -85
	ERR_MSG_LEVEL_TOO_LOW("send pm level too low"), // -84
	ERR_NO_GUILD("-78"),
	ERR_SERVER_DOWN("server not available"), // -69
	ERR_JOINED_TOO_RECENTLY("not 24 hours member"), // -68
	ERR_REVOLT_FAILED("-67"),
	ERR_STOP_TUNNELING("-66"),
	ERR_SESSION_ID_EXPIRED("sessionid invalid"), // -65
	ERR_GUILD_ATTACK_STATUS("-64"),
	ERR_GUILD_ALREADY_ATTACKING("-63"),
	ERR_GUILD_ATTACK_DELAY("-62"),
	ERR_GUILD_ALREADY_UNDER_ATTACK("already under attack"), // -61
	ERR_GUILD_FIGHT_TOO_EXPENSIVE("need more gold"), // -60
	ERR_INVENTORY_FULL("need free backpack slot"), // -58
	ERR_PLACE_BET("-57"),
	ERR_ACCOUNTS_PER_IP("-56"),
	ERR_TOO_SOON("cannot do this right now"), // -55
	ERR_LOCKED_ADMIN("admin lock"), // -54
	ERR_LOCKED_PAYMENT("payment lock"), // -53
	ERR_GUILD_DONATE_FRA("-52"),
	ERR_GUILD_DONATE_NEG("-51"),
	ERR_VALIDATE("valid email required"), // -50
	ERR_REQUEST_PW("-49"),
	ERR_ATTACK_AGAIN("-48"),
	ERR_GUILD_MUSH_FREE("-47"),
	ERR_GUILD_EMAIL_VALIDATE("-46"),
	ERR_GUILD_NAME_CHARACTERS("-45"),
	ERR_GUILD_NAME_LENGTH("-44"),
	ERR_GUILD_NAME_REJECTED("groupname is not available"), // -43
	ERR_BOOST("-42"),
	ERR_NO_MUSH_MQ("-41"),
	ERR_NO_MUSH_PVP("-40"),
	ERR_NOT_INVITED("-39"),
	ERR_GUILD_ALREADY_MEMBER("-38"),
	ERR_WORSE_MOUNT("-37"),
	ERR_NO_ENDURANCE("need more adventurelust"), // -36
	ERR_NO_MUSH_BAR("-35"),
	ERR_BEER("-34"),
	ERR_GUILD_CHAT_TEXT_ERROR("-33"),
	ERR_GUILD_CHAT_HISTORY("-32"),
	ERR_GUILD_CHAT_NOT_MEMBER("this player is not in your group"), // -31
	ERR_GUILD_TOO_EXPENSIVE("need more gold"), // -30
	ERR_SUBJECT_TOO_SHORT("-29"),
	ERR_GUILD_PLAYER_NOT_FOUND("player not found"), // -28
	ERR_GUILD_ALREADY_YOU_THIS("-27"),
	ERR_GUILD_NOT_REAL_MEMBER("-26"),
	ERR_GUILD_ALREADY_YOU_OTHER("-25"),
	ERR_GUILD_IS_FULL("-24"),
	ERR_GUILD_MASTER_CANT_BE_OFFICER("-23"),
	ERR_GUILD_NOT_MEMBER("-22"),
	ERR_GUILD_BUILDING_MAX("-21"),
	ERR_GUILD_BUILDING_NOT_FOUND("-20"),
	ERR_GUILD_LACK_GOLD("-19"),
	ERR_GUILD_LACK_MUSH("-18"),
	ERR_GUILD_NOT_ALLOWED("-17"),
	ERR_GUILD_NOT_FOUND("group not found"), // -16
	ERR_FIGHT_SELF("-15"),
	ERR_NO_INDEX_FREE("-14"),
	ERR_MAIL_EXISTS("mail not available"), // -12
	ERR_GENDER_OR_RACE("-11"),
	ERR_EMAIL_WRONG("mail is wrong"), // -10
	ERR_FACE_DATA_INCORRECT("-9"),
	ERR_WRONG_PASSWORD("wrong pass"), // -8
	ERR_TOO_EXPENSIVE_GOLD("need more gold"), // -7
	ERR_LOGIN_FAILED("player not found"), // -6
	ERR_NAME_REJECTED("-5"),
	ERR_EMAIL_REJECTED("-4"),
	ERR_PASSWORD_TOO_SHORT("password too short"), // -3
	ERR_NAME_TOO_SHORT("-2"),
	ERR_NAME_EXISTS("character exists"), // -1
	ERR_CRYPTID_NOT_FOUND("cryptoid not found"),
	NONE("0"),
	ACCOUNT_CREATE("1"),
	ACCOUNT_SUCCESS("1"),
	LOGIN("2"),
	LOGIN_SUCCESS("2"),
	FAME_LIST("3"),
	FORGOT_PASSWORD("3"),
	SCREEN_BUILDCHAR("4"),
	SCREEN_CHAR("4"),
	SCREEN_POST("5"),
	SCREEN_GILDEN("6"),
	SCREEN_EHRENHALLE("7"),
	SCREEN_WELTKARTE("8"),
	SCREEN_OPTIONEN("9"),
	SCREEN_TAVERNE("10"),
	SCREEN_ARENA("11"),
	SCREEN_ARBEITEN("12"),
	SCREEN_SCHMIEDE("13"),
	SCREEN_ZAUBERLADEN("14"),
	SCREEN_STALL("15"),
	SCREEN_PILZDEALER("16"),
	SCREEN_GILDE_GRUENDEN("17"),
	BUY_MOUNT("20"),
	BUY_ATTRIB("21"),
	PLACE_BET("22"),
	SCREEN_FREMDGILDE("23"),
	SCREEN_GILDENHALLE("24"),
	DEALER_AKTION("25"),
	DEALER_SPONSOR("26"),
	KILL_POTION("27"),
	GUILD_DATA("101"),
	GUILD_FOUND("101"),
	GUILD_DELETE("102"),
	SAVEGAME_STAY("102"),
	ARBEIT_ERLEDIGT("103"),
	GUILD_INVITE("103"),
	ARBEIT_START("104"),
	GUILD_EXPEL("104"),
	ARBEIT_STOP("105"),
	GUILD_SET_MASTER("105"),
	ARENA_ATTACK("106"),
	GUILD_SET_OFFICER("106"),
	QUEST_DONE("106"),
	GUILD_IMPROVE("107"),
	QUEST_START("107"),
	GUILD_SET_DESC("108"),
	QUEST_STOP("108"),
	GUILD_RENAME("109"),
	PLAYER_DESC_SUCCESS("109"),
	GUILD_JOIN("110"),
	PLAYER_SCREEN("111"),
	ERR_PLAYER_NOT_FOUND("player not found"), // 112
	GUILD_JOIN_ATTACK("112"),
	DEMO_SCREEN("113"),
	GUILD_JOIN_DEFENSE("113"),
	ATTACK_NOT_EXIST("114"),
	GUILD_COMMENCE_ATTACK("114"),
	CHANGE_FACE_OK("115"),
	INVITE_PLAYER("115"),
	ALBUM("116"),
	CHANGE_PASS_OK("116"),
	CHANGE_NAME_OK("117"),
	CHANGE_MAIL_OK("118"),
	DELETE_ACCOUNT_OK("119"),
	NO_LOGIN("120"),
	RESP_REQUEST_GUILD("121"),
	Resp_Dungeon("122"),
	GUILD_FOUND_SUCCESS("150"),
	GUILD_DELETE_SUCCESS("151"),
	GUILD_RENAME_SUCCESS("152"),
	GUILD_CHANGE_DESC_SUCCESS("153"),
	GUILD_IMPROVE_SUCCESS("154"),
	GUILD_OFFICER_SUCCESS("155"),
	GUILD_EXPEL_SUCCESS("156"),
	GUILD_INVITE_SUCCESS("157"),
	GUILD_JOIN_SUCCESS("158"),
	GUILD_MASTER_SUCCESS("159"),
	GUILD_DONATE_SUCCESS("160"),
	CHAT_HISTORY("161"),
	CHAT_LINE("162"),
	TRANS_COUNT("163"),
	EMAIL_RESENT("164"),
	PASSWORD_SENT("165"),
	VALIDATE_OK("166"),
	UPDATE_CHECK("167"),
	BET_WON("168"),
	BET_LOST("169"),
	RESP_SCREEN_GILDENHALLE("170"),
	OTHER_GUILD("172"),
	SAVEGAME_STAY_ERROR("173"),
	GUILD_FIGHT("178"),
	GUILD_JOIN_ATTACK_OK("179"),
	GUILD_JOIN_DEFENSE_OK("180"),
	GUILD_COMMENCE_ATTACK_OK("181"),
	GUILD_NAMES("183"),
	LOGIN_SUCCESS_BOUGHT("184"),
	REQUEST_GUILD_QUIET("186"),
	LOGOUT_SUCCESS("187"),
	QUEST_DONE_PIXEL("188"),
	QUEST_SKIP("189"),
	WHISPER_SUCCESS("190"),
	INVITE_SUCCESS("191"),
	RESP_ALBUM("192"),
	QUEST_SKIP_ALLOWED("193"),
	QUEST_SKIP_ALLOWED_START("194"),
	BUY_LUXURY("195"),
	LOAD_CATAPULT("196"),
	QUEST_DONE_PIXEL_2("197"),
	ARENA_DEFENSE("201"),
	READ_MESSAGE("201"),
	MESSAGE_SENT("202"),
	INBOX_FULL("203"),
	RECIPIENT_NOT_FOUND("send pm player not found"), // 204
	RECIPIENT_SELF("205"),
	TOILET_FLUSH("302"),
	SCREEN_TOILET("303"),
	TOILET_LOCKED("304"),
	TOILET_DROPPED("305"),
	TOILET_FULL("toilett is full"), // 306
	TOILET_FLUSHED("308"),
	TOILET_UNLOCKED("309"),
	TOILET_TANKFULL("311"),
	SCREEN_TOWER("312"),
	ROB_PLAYER("313"),
	TOWER_TRY("313"),
	COPYCAT_BOOST("314"),
	TOWER_SAVE("315"),
	SAVEGAME_SHARD("316"),
	SAVEGAME_MIRROR("317"),
	MOVE_COPYCAT_ITEM("318"),
	MOVE_TOWER_ITEM("319"),
	TOWER_FIGHT("321"),
	RESP_SCREEN_WITCH("324"),
	ERR_TOILET_DROPTWICE("items cannot be flushed twice"), // 357
	RESP_PORTAL_FIGHT("359"),
	RESP_PORTAL_FIGHT_SINGLE("361"),
	ERR_LOGIN_COUNT_TOO_LOW("login count too low"), // 362
	ERR_GUILD_ATTACK_NOT_FOUND("group does not exist"), // 363
	ERR_INVENTORY_FULL_2("need a free slot"), // 364
	ERR_PASS_SEC_OUT("password security is outdated"), // 365
	ERR_TOO_EXPENSIVE_MUSH("need more coins"), // 366
	ERR_GUILD_ATTACK_3000_POINTS("3000 points"), // 367
	CHAR_CREATE("501"),
	ARBEIT("502"),
	REQUEST_GUILD("503"),
	INVENTORY_CHANGE("504"),
	ARBEIT_CANCEL("505"),
	REQUEST_NEWWAREZ("506"),
	POST_READ("507"),
	POST_DELETE("508"),
	POST_SEND("509"),
	QUEST_BEGIN("510"),
	QUEST_CANCEL("511"),
	START_FIGHT("512"),
	REQUEST_CHAR("513"),
	SET_PLAYER_DESC("514"),
	RE_LOGIN("515"),
	SEND_CHAT("516"),
	GET_CHAT_HISTORY("517"),
	BUY_BEER("518"),
	MAINQUEST("519"),
	REQUEST_TRANS_COUNT("530"),
	RESEND_EMAIL("531"),
	VALIDATE("532"),
	REQUEST_GUILD_NAMES("533"),
	REVOLT("534"),
	LOGOUT("535"),
	POST_SEND_GUILD("536"),
	WHISPER("537"),
	CHANGE_FACE("801"),
	DELETE_ACCOUNT("802"),
	CHANGE_NAME("803"),
	CHANGE_MAIL("804"),
	CHANGE_PASS("805"),
	NO_RESP_TYPE("999"),
	WAGESPERHOUR("wagesperhour");

	private final String value;

	private ResponseEnum(String value) {
		this.value = value;
	}

	@Override
	public String toString() {
		return this.value;
	}

	public static ResponseEnum fromString(String text) {
		ResponseEnum value = null;

		if (text != null) {
			for (ResponseEnum responseType : ResponseEnum.values()) {
				if (text.equalsIgnoreCase(responseType.value)) {
					value = responseType;
				}
			}
		}

		return value;
	}
}
